# SPDX-License-Identifier: 0BSD

name: Examples

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  examples:
    name: ${{ matrix.distribution }} latest
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution: Ubuntu
            image: ubuntu:latest
            make_args: >-
              CXX=clang++-22
              CXX_MODULE_SCANNER=clang-scan-deps-22
            install: >-
              apt-get update &&
              DEBIAN_FRONTEND=noninteractive apt-get install --yes
              clang-22 clang-tools-22 git libc++-22-dev libc++abi-22-dev jq make
          - distribution: Fedora
            image: fedora:latest
            make_args: CXX=clang++
            install: >-
              dnf install --assumeyes
              clang clang-tools-extra gcc-c++ git
              libcxx-devel libcxxabi-devel jq make

    steps:
      - name: Install dependencies
        run: ${{ matrix.install }}

      - uses: actions/checkout@v7

      - name: Test examples
        run: make --jobs check ${{ matrix.make_args }}

      - name: Test examples with GCC
        if: matrix.distribution == 'Fedora'
        run: |
          make clean CXX=g++
          make --jobs check CXX=g++
